#    "$Name:  $";
#    "$Header:  $";
#=============================================================================
#
# file :        PyAlbaEm.py
#
# description : Python source for the PyAlbaEm and its commands. 
#                The class is derived from Device. It represents the
#                CORBA servant object which will be accessed from the
#                network. All commands which can be executed on the
#                PyAlbaEm are implemented in this file.
#
# project :     TANGO Device Server
#
# $Author:  $
#
# $Revision:  $
#
# $Log:  $
#
# copyleft :    European Synchrotron Radiation Facility
#               BP 220, Grenoble 38043
#               FRANCE
#
#=============================================================================
#          This file is generated by POGO
#    (Program Obviously used to Generate tango Object)
#
#         (c) - Software Engineering Group - ESRF
#=============================================================================
#


import PyTango
import sys
import math
from AlbaEmLib import albaem
#from fandango.dynamic import *
import fandango
import logging
import logging.handlers

#==================================================================
#   PyAlbaEm Class Description:
#
#         Device Server for the Alba Electrometer
#
#==================================================================

#==================================================================
#   Device States Description:
#
#   DevState.ON :
#   DevState.UNKNOWN :
#==================================================================


class PyAlbaEm(fandango.DynamicDS):

#--------- Add you global variables here --------------------------

#------------------------------------------------------------------
#    Device constructor
#------------------------------------------------------------------
    def __init__(self,cl, name):
        #PyTango.Device_4Impl.__init__(self,cl,name)
        fandango.DynamicDS.__init__(self,cl,name,_locals={
                                                          #'I2': lambda: (lambda attr: [self.read_I2(attr),attr][1].value)(fandango.tango.fakeAttributeValue()),
                                                          'READMEASURE': lambda axis: self.readMeasure(axis),
                                                          'READBUFFERCHANNEL': lambda axis: self.readBufferChannel(axis),
                                                          'READBUFFERMEAN' : lambda axis: self.readBufferMean(axis)
                                                          },useDynStates=True)
        PyAlbaEm.init_device(self)

#------------------------------------------------------------------
#    Device destructor
#------------------------------------------------------------------
    def delete_device(self):
        print "[Device delete_device method] for device",self.get_name()


#------------------------------------------------------------------
#    Device initialization
#------------------------------------------------------------------
    def init_device(self):
        print "In ", self.get_name(), "::init_device()"
        self.get_DynDS_properties()
        self.AllRanges = [0,0,0,0] #used to reduce the number of readings from electrometer.
        self._allMeasures =[0,0,0,0]
        self._channelsNames = ['I1','I2','I3','I4'] #@todo: check why memorized is not working
        self.__numOfPoints = 0
        self.attr_I1_read = None
        self.attr_I2_read = None
        self.attr_I3_read = None
        self.attr_I4_read = None
        try:
            self.set_state(PyTango.DevState.ON)
            self.get_device_properties(self.get_device_class())
            self.AlbaElectr = albaem(self.AlbaEmName)
            
            if self.LogFileName != "" or self.LogFileName == None or self.LogFileName == []:
                DftLogFormat = '%(threadName)-14s %(levelname)-8s %(asctime)s %(name)s: %(message)s'
                myFormat = logging.Formatter(DftLogFormat)
                self.my_logger = logging.getLogger('albaEM DS') #@note: Not too clear the difference between getLogger() and Logger()
                self.my_logger.setLevel(logging.DEBUG)
                handler = logging.handlers.RotatingFileHandler(self.LogFileName, maxBytes=10240, backupCount=5)
                handler.setFormatter(myFormat)
                self.my_logger.addHandler(handler)
                
                self.AlbaElectr.logger.addHandler(handler)
            
            self.AlbaElectr.setEnablesAll('YES')
            state = self.AlbaElectr.getState()
            if state == 'IDLE':
                self.AlbaElectr.StartAdc()
            elif state == 'ON':
                #@warning: super chapuza para evitar errores de lecturas en las medias de los buffer
                self.AlbaElectr.setPoints(1)
                self.AlbaElectr.Start()
            elif state == 'RUNNING':
                self.AlbaElectr.Stop()
                self.AlbaElectr.setPoints(1)
                self.AlbaElectr.Start()
                
            
        except Exception, e:
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in init_device: %s", e)


#------------------------------------------------------------------
#    Always excuted hook method
#------------------------------------------------------------------
    def always_executed_hook(self):
        print "In ", self.get_name(), "::always_excuted_hook()"
        fandango.DynamicDS.always_executed_hook(self)
        #self.set_state(PyTango.DevState.ON) 
        self.checkAlbaEmState()


#==================================================================
#
#    PyAlbaEm read/write attribute methods
#
#==================================================================
#------------------------------------------------------------------
#    Read Attribute Hardware
#------------------------------------------------------------------
    def read_attr_hardware(self,data):
        print "In ", self.get_name(), "::read_attr_hardware()"



#------------------------------------------------------------------
#    Read I1 attribute
#------------------------------------------------------------------
    def read_I1(self, attr):
        print "In ", self.get_name(), "::read_I1()"
        
        #    Add your own code here
        try:
            self.attr_I1_read = float(self.AlbaElectr.getMeasure('1'))
            attr.set_value(self.attr_I1_read)

        except Exception, e:
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in read_I1: %s", e)


#------------------------------------------------------------------
#    Read I2 attribute
#------------------------------------------------------------------
    def read_I2(self, attr):
        print "In ", self.get_name(), "::read_I2()"
        
        #    Add your own code here
        try:
            self.attr_I2_read = float(self.AlbaElectr.getMeasure('2'))
            attr.set_value(self.attr_I2_read)

        except Exception, e:
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in read_I2: %s", e)


#------------------------------------------------------------------
#    Read I3 attribute
#------------------------------------------------------------------
    def read_I3(self, attr):
        print "In ", self.get_name(), "::read_I3()"
        
        #    Add your own code here
        try:
            self.attr_I3_read = float(self.AlbaElectr.getMeasure('3'))
            attr.set_value(self.attr_I3_read)
        except Exception, e:
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in read_I3: %s", e)


#------------------------------------------------------------------
#    Read I4 attribute
#------------------------------------------------------------------
    def read_I4(self, attr):
        print "In ", self.get_name(), "::read_I4()"
        
        #    Add your own code here
       
        try:
            self.attr_I4_read = float(self.AlbaElectr.getMeasure('4'))
            attr.set_value(self.attr_I4_read)
        except Exception, e:
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in read_I4: %s", e)

#------------------------------------------------------------------
#    Read AllChannels attribute
#------------------------------------------------------------------
    def read_AllChannels(self, attr):
        print "In ", self.get_name(), "::read_AllChannels()"
        
        #    Add your own code here
        try:
            measures, self.status = self.AlbaElectr.getMeasuresAll()
            for i,value in enumerate(measures): 
                self._allMeasures[i] = float(value[1])
            attr.set_value(self._allMeasures, 4)
        except Exception, e:
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in read_AllChannels: %s", e)

#------------------------------------------------------------------
#    Read LastValues attribute
#------------------------------------------------------------------
    def read_LastValues(self, attr):
        print "In ", self.get_name(), "::read_LastValues()"
        
        #    Add your own code here
        try:
            _lastValues = ['0','0','0','0']
            lastValues = self.AlbaElectr.getLdata()
            for i,value in enumerate(lastValues[0]): 
                _lastValues[i] = float(value[1])
            attr.set_value(_lastValues, 4)
        except Exception, e:
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in read_LastValues: %s", e)
#------------------------------------------------------------------
#    Read range_ch1 attribute
#------------------------------------------------------------------
    def read_range_ch1(self, attr):
        print "In ", self.get_name(), "::read_range_ch1()"
        
        #    Add your own code here
        try:
            rgs = self.AlbaElectr.getRanges(['1'])
            attr_range_ch1_read = rgs[0]
            attr.set_value(attr_range_ch1_read[1])
            self.AllRanges[0] = attr_range_ch1_read[1]
            if self.attr_I1_read != None:
                self.checkRanges(attr,self.attr_I1_read,0)
        except Exception, e:
            #print("Error reading range_ch1!: %s" %e)
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in read_range_ch1: %s", e)


#------------------------------------------------------------------
#    Write range_ch1 attribute
#------------------------------------------------------------------
    def write_range_ch1(self, attr):
        print "In ", self.get_name(), "::write_Ranges()"
        
        data=[]
        attr.get_write_value(data)
        print "Attribute value = ", data
        print type(data[0])

        #    Add your own code here
        self.AlbaElectr.setRanges([['1', data[0]]])
        self.AllRanges[0] = data[0]
        print str(self.AlbaElectr.getRanges(['1']))

#------------------------------------------------------------------
#    Read range_ch2 attribute
#------------------------------------------------------------------
    def read_range_ch2(self, attr):
        print "In ", self.get_name(), "::read_range_ch2()"
        
        #    Add your own code here
        try:
            rgs = self.AlbaElectr.getRanges(['2'])
            attr_range_ch2_read = rgs[0]
            attr.set_value(attr_range_ch2_read[1])
            self.AllRanges[1] = attr_range_ch2_read[1]
            if self.attr_I2_read != None:
                self.checkRanges(attr,self.attr_I2_read,1)
        except Exception, e:
            #print("Error reading range_ch2!: %s" %e)
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in read_range_ch2: %s", e)


#------------------------------------------------------------------
#    Write range_ch2 attribute
#------------------------------------------------------------------
    def write_range_ch2(self, attr):
        print "In ", self.get_name(), "::write_Ranges()"
        
        data=[]
        attr.get_write_value(data)
        print "Attribute value = ", data

        #    Add your own code here
        self.AlbaElectr.setRanges([['2', data[0]]])
        self.AllRanges[1] = data[0]
        print str(self.AlbaElectr.getRanges(['2']))

#------------------------------------------------------------------
#    Read range_ch3 attribute
#------------------------------------------------------------------
    def read_range_ch3(self, attr):
        print "In ", self.get_name(), "::read_range_ch3()"
        
        #    Add your own code here
        try:
            rgs = self.AlbaElectr.getRanges(['3'])
            attr_range_ch3_read = rgs[0]
            attr.set_value(attr_range_ch3_read[1])
            self.AllRanges[2] = attr_range_ch3_read[1]
            if self.attr_I3_read != None:
                self.checkRanges(attr,self.attr_I3_read,2)
        except Exception, e:
            #print("Error reading range_ch3!: %s" %e)
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in read_range_ch3: %s", e)


#------------------------------------------------------------------
#    Write range_ch3 attribute
#------------------------------------------------------------------
    def write_range_ch3(self, attr):
        print "In ", self.get_name(), "::write_Ranges()"
        
        data=[]
        attr.get_write_value(data)
        print "Attribute value = ", data

        #    Add your own code here        
        self.AlbaElectr.setRanges([['3', data[0]]])
        self.AllRanges[2] = data[0]
        print str(self.AlbaElectr.getRanges(['3']))

#------------------------------------------------------------------
#    Read range_ch4 attribute
#------------------------------------------------------------------
    def read_range_ch4(self, attr):
        print "In ", self.get_name(), "::read_range_ch4()"
        
        #    Add your own code here
        try:
            rgs = self.AlbaElectr.getRanges(['4'])
            attr_range_ch4_read = rgs[0]
            attr.set_value(attr_range_ch4_read[1])
            self.AllRanges[3] = attr_range_ch4_read[1]
            if self.attr_I4_read != None:
                self.checkRanges(attr,self.attr_I4_read,3)
        except Exception, e:
            #print("Error reading range_ch4!: %s" %e)
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in read_range_ch4: %s", e)


#------------------------------------------------------------------
#    Write range_ch4 attribute
#------------------------------------------------------------------
    def write_range_ch4(self, attr):
        print "In ", self.get_name(), "::write_Ranges()"
        
        data=[]
        attr.get_write_value(data)
        print "Attribute value = ", data

        #    Add your own code here
        self.AlbaElectr.setRanges([['4', data[0]]])
        self.AllRanges[3] = data[0]
        print str(self.AlbaElectr.getRanges(['4']))

#------------------------------------------------------------------
#    Read Ranges attribute
#------------------------------------------------------------------
    def read_Ranges(self, attr):
        print "In ", self.get_name(), "::read_Ranges()"
        
        #    Add your own code here
        try:
            rgs = self.AlbaElectr.getRanges(['1','2','3','4'])
            for i,r in enumerate(rgs): 
                self.AllRanges[i] = r[1]
            attr_Ranges_read = self.AllRanges
            attr.set_value(attr_Ranges_read, 4)
        except Exception, e:
            #print("Erroooooooor!!!!!: %s" %e)
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in read_Ranges: %s", e)


#------------------------------------------------------------------
#    Write Ranges attribute
#------------------------------------------------------------------
    def write_Ranges(self, attr):
        print "In ", self.get_name(), "::write_Ranges()"
        data=[]
        attr.get_write_value(data)
        print "Attribute value = ", data

        #    Add your own code here
        d = data[0].split(',')
        ranges = []
        for i,range in enumerate(d):
            r = [str(i+1),d[i]]
            ranges.append(r)
            self.AllRanges[i] = d[i]
        #iranges = data.split()
        #ranges = [['1', iranges[0]], ['2', iranges[1]], ['3', iranges[2]], ['4', iranges[3]]]
        print "Ranges to write: %s" %ranges
        self.AlbaElectr.setRanges(ranges)

        print str(self.AlbaElectr.getRanges(['1','2','3','4']))

#------------------------------------------------------------------
#    Read filter_ch1 attribute
#------------------------------------------------------------------
    def read_filter_ch1(self, attr):
        print "In ", self.get_name(), "::read_filter_ch1()"
        
        #    Add your own code here
        try:
            fltr = self.AlbaElectr.getFilters(['1'])
            attr_filter_ch1_read = fltr[0]
            attr.set_value(attr_filter_ch1_read[1])
        except Exception, e:
            #print("Error reading filter_ch1!: %s" %e)
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in read_filter_ch1: %s", e)


#------------------------------------------------------------------
#    Write filter_ch1 attribute
#------------------------------------------------------------------
    def write_filter_ch1(self, attr):
        print "In ", self.get_name(), "::write_filter_ch1()"
        
        data=[]
        attr.get_write_value(data)
        print "Attribute value = ", data

        #    Add your own code here
        self.AlbaElectr.setFilters([['1', data[0]]])
        print str(self.AlbaElectr.getFilters(['1']))


#------------------------------------------------------------------
#    Read filter_ch2 attribute
#------------------------------------------------------------------
    def read_filter_ch2(self, attr):
        print "In ", self.get_name(), "::read_filter_ch2()"
        
        #    Add your own code here
        try:
            fltr = self.AlbaElectr.getFilters(['2'])
            attr_filter_ch2_read = fltr[0]
            attr.set_value(attr_filter_ch2_read[1])
        except Exception, e:
            #print("Error reading filter_ch2!: %s" %e)
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in read_filter_ch2: %s", e)


#------------------------------------------------------------------
#    Write filter_ch2 attribute
#------------------------------------------------------------------
    def write_filter_ch2(self, attr):
        print "In ", self.get_name(), "::write_filter_ch2()"
        
        data=[]
        attr.get_write_value(data)
        print "Attribute value = ", data

        #    Add your own code here
        self.AlbaElectr.setFilters([['2', data[0]]])
        print str(self.AlbaElectr.getFilters(['2']))


#------------------------------------------------------------------
#    Read filter_ch3 attribute
#------------------------------------------------------------------
    def read_filter_ch3(self, attr):
        print "In ", self.get_name(), "::read_filter_ch3()"
        
        #    Add your own code here
        try:
            fltr = self.AlbaElectr.getFilters(['3'])
            attr_filter_ch3_read = fltr[0]
            attr.set_value(attr_filter_ch3_read[1])
        except Exception, e:
            #print("Error reading filter_ch3!: %s" %e)
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in read_filter_ch3: %s", e)


#------------------------------------------------------------------
#    Write filter_ch3 attribute
#------------------------------------------------------------------
    def write_filter_ch3(self, attr):
        print "In ", self.get_name(), "::write_filter_ch3()"
        
        data=[]
        attr.get_write_value(data)
        print "Attribute value = ", data

        #    Add your own code here
        self.AlbaElectr.setFilters([['3', data[0]]])
        print str(self.AlbaElectr.getFilters(['3']))

#------------------------------------------------------------------
#    Read filter_ch4 attribute
#------------------------------------------------------------------
    def read_filter_ch4(self, attr):
        print "In ", self.get_name(), "::read_filter_ch4()"
        
        #    Add your own code here
        try:
            fltr = self.AlbaElectr.getFilters(['4'])
            attr_filter_ch4_read = fltr[0]
            attr.set_value(attr_filter_ch4_read[1])
        except Exception, e:
            #print("Error reading filter_ch4!: %s" %e)
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in read_filter_ch4: %s", e)


#------------------------------------------------------------------
#    Write filter_ch4 attribute
#------------------------------------------------------------------
    def write_filter_ch4(self, attr):
        print "In ", self.get_name(), "::write_filter_ch4()"
        
        data=[]
        attr.get_write_value(data)
        print "Attribute value = ", data

        #    Add your own code here
        self.AlbaElectr.setFilters([['4', data[0]]])
        print str(self.AlbaElectr.getFilters(['4']))

#------------------------------------------------------------------
#    Read Filters attribute
#------------------------------------------------------------------
    def read_Filters(self, attr):
        print "In ", self.get_name(), "::read_Filters()"
        
        #    Add your own code here
        try:
            fltrs = self.AlbaElectr.getFiltersAll()
            fltrsList = []
            for i in fltrs: fltrsList.append(i[1])
            attr_Filters_read = fltrsList
            attr.set_value(attr_Filters_read, 4)
        except Exception, e:
            #print("Error reading Filters!: %s" %e)
            self.set_state(PyTango.DevState.FAULT)
            self.my_logger.error("Exception in read_Filters: %s", e)


#------------------------------------------------------------------
#    Write Filters attribute
#------------------------------------------------------------------
    def write_Filters(self, attr):
        print "In ", self.get_name(), "::write_Filters()"
        data=[]
        attr.get_write_value(data)
        print "Attribute value = ", data

        #    Add your own code here
        d = data[0].split(',')
        filters = []
        for i,filter in enumerate(d):
            f = [str(i+1),d[i]]
            filters.append(f)
        print "Filters to write: %s" %filters
        self.AlbaElectr.setFiltersAll(filters)

        print str(self.AlbaElectr.getFiltersAll())
        
#------------------------------------------------------------------
#    Read ChannelsNames attribute
#------------------------------------------------------------------
    def read_ChannelsNames(self, attr):
        print "In ", self.get_name(), "::read_ChannelsNames()"
        
        #    Add your own code here
        attr.set_value(self._channelsNames, 4)

#------------------------------------------------------------------
#    Write ChannelsNames attribute
#------------------------------------------------------------------
    def write_ChannelsNames(self, attr):
        print "In ", self.get_name(), "::write_ChannelsNames()"
        data=[]
        attr.get_write_value(data)
        print "Attribute value = ", data

        #    Add your own code here
        #names = data.split(',')
        self._channelsNames = data
        print str(self._channelsNames)
        
##------------------------------------------------------------------
##    Read LogRecord attribute
##------------------------------------------------------------------
#    def read_LogRecord(self, attr):
#        print "In ", self.get_name(), "::read_LogRecord()"
#        
#        #    Add your own code here
#        logState = self.AlbaElectr.logger.getRecordState()
#        attr.set_value(logState)
#
##------------------------------------------------------------------
##    Write LogRecord attribute
##------------------------------------------------------------------
#    def write_LogRecord(self, attr):
#        print "In ", self.get_name(), "::write_LogRecord()"
#        data=[]
#        attr.get_write_value(data)
#        print "Attribute value = ", data
#
#        #    Add your own code here
#        self.AlbaElectr.logger.setRecordState(data)
#        print str(self.AlbaElectr.logger.getRecordState())
#        
        
#------------------------------------------------------------------
#    Read TriggerMode attribute
#------------------------------------------------------------------
    def read_TriggerMode(self, attr):
        print "In ", self.get_name(), "::read_TriggerMode()"
        
        #    Add your own code here
        try:
            mode = self.AlbaElectr.getTrigmode()
            attr.set_value(mode)
        except Exception,e:
            self.my_logger.error("Exception reading TriggerMode: %s", e)
            self.set_state(PyTango.DevState.FAULT)

#------------------------------------------------------------------
#    Write TriggerMode attribute
#------------------------------------------------------------------
    def write_TriggerMode(self, attr):
        print "In ", self.get_name(), "::write_TriggerMode()"
        data=[]
        attr.get_write_value(data)
        print "Attribute value = ", data

        #    Add your own code here
        try:
            self.AlbaElectr.setTrigmode(data[0])
            print str(data[0])
        except Exception, e:
            self.my_logger.error("Exception setting trigger mode: %s",e)
            raise
        
#------------------------------------------------------------------
#    Read TriggerPeriod attribute
#------------------------------------------------------------------
    def read_TriggerPeriod(self, attr):
        print "In ", self.get_name(), "::read_TriggerPeriode()"
        
        #    Add your own code here
        try:
            period = float(self.AlbaElectr.getTrigperiod())
            period = period/1000.0
            attr.set_value(period)
        except Exception,e:
            self.my_logger.error("Exception reading TriggerPeriod: %s", e)
            self.set_state(PyTango.DevState.FAULT)

#------------------------------------------------------------------
#    Write TriggerPeriod attribute
#------------------------------------------------------------------
    def write_TriggerPeriod(self, attr):
        print "In ", self.get_name(), "::write_TriggerPeriod()"
        data=[]
        attr.get_write_value(data)
        print "Attribute value = ", data

        #    Add your own code here
        try:
            period = data[0]*1000.0
            self.AlbaElectr.setTrigperiod(period)
            print str(period)
        except Exception, e:
            self.my_logger.error("Exception setting trigger period: %s",e)
            raise

#------------------------------------------------------------------
#    Read BufferSize attribute
#------------------------------------------------------------------
    def read_BufferSize(self, attr):
        print "In ", self.get_name(), "::read_BufferSize()"
        
        #    Add your own code here
        try:
            self.__numOfPoints = int(self.AlbaElectr.getPoints())
            attr.set_value(self.__numOfPoints)
        except Exception,e:
            self.my_logger.error("Exception reading BufferSize: %s", e)
            self.set_state(PyTango.DevState.FAULT)

#------------------------------------------------------------------
#    Write BufferSize attribute
#------------------------------------------------------------------
    def write_BufferSize(self, attr):
        print "In ", self.get_name(), "::write_BufferSize()"
        data=[]
        attr.get_write_value(data)
        print "Attribute value = ", data

        #    Add your own code here
        try:
            self.__numOfPoints = data[0]
            self.AlbaElectr.setPoints(self.__numOfPoints)
            print str(self.__numOfPoints)
        except Exception, e:
            self.my_logger.error("Exception setting BufferSize: %s",e)
            raise 
  
#------------------------------------------------------------------
#    Read AvSamples attribute
#------------------------------------------------------------------
    def read_AvSamples(self, attr):
        print "In ", self.get_name(), "::read_AvSamples()"
        
        #    Add your own code here
        try:
            avSamples = float(self.AlbaElectr.getAvsamples())
            avSamples = avSamples/1000
            attr.set_value(avSamples)
        except Exception,e:
            self.my_logger.error("Exception reading AvSamples: %s", e)
            self.set_state(PyTango.DevState.FAULT)

#------------------------------------------------------------------
#    Write AvSamples attribute
#------------------------------------------------------------------
    def write_AvSamples(self, attr):
        print "In ", self.get_name(), "::write_AvSamples()"
        data=[]
        attr.get_write_value(data)
        print "Attribute value = ", data

        #    Add your own code here
        try:
            avSamples = data[0]*1000
            self.AlbaElectr.setAvsamples(avSamples)
            print str(avSamples)
        except Exception, e:
            self.my_logger.error("Exception setting AvSamples: %s",e)
            raise  

#------------------------------------------------------------------
#    Read BufferI1 attribute
#------------------------------------------------------------------
    def read_BufferI1(self, attr):
        print "In ", self.get_name(), "::read_BufferI1()"
        
        #    Add your own code here
        try:
            data = self.AlbaElectr.getBufferChannel(1)
            length = len(data)
            attr.set_value(data, length)
        except Exception, e:
            self.my_logger.error("Exception reading BufferI1: %s", e)
            raise

#------------------------------------------------------------------
#    Read BufferI1Mean attribute
#------------------------------------------------------------------
    def read_BufferI1Mean(self, attr):
        print "In ", self.get_name(), "::read_BufferI1Mean()"
        
        #    Add your own code here
        try:
            data = self.AlbaElectr.getBufferChannel(1)
            length = len(data)
            mean = sum(data) / length
            attr.set_value(mean)
        except Exception, e:
            self.my_logger.error("Exception reading BufferI1Mean: %s", e)
            raise

#------------------------------------------------------------------
#    Read BufferI2 attribute
#------------------------------------------------------------------
    def read_BufferI2(self, attr):
        print "In ", self.get_name(), "::read_BufferI2()"
        
        #    Add your own code here
        try:
            data = self.AlbaElectr.getBufferChannel(2)
            length = len(data)
            attr.set_value(data, length)
        except Exception, e:
            self.my_logger.error("Exception reading BufferI2: %s", e)
            raise

#------------------------------------------------------------------
#    Read BufferI2Mean attribute
#------------------------------------------------------------------
    def read_BufferI2Mean(self, attr):
        print "In ", self.get_name(), "::read_BufferI2Mean()"
        
        #    Add your own code here
        try:
            data = self.AlbaElectr.getBufferChannel(2)
            length = len(data)
            mean = sum(data) / length
            attr.set_value(mean)
        except Exception, e:
            self.my_logger.error("Exception reading BufferI2Mean: %s", e)
            raise

#------------------------------------------------------------------
#    Read BufferI2 attribute
#------------------------------------------------------------------
    def read_BufferI3(self, attr):
        print "In ", self.get_name(), "::read_BufferI3()"
        
        #    Add your own code here
        try:
            data = self.AlbaElectr.getBufferChannel(3)
            length = len(data)
            attr.set_value(data, length)
        except Exception, e:
            self.my_logger.error("Exception reading BufferI3: %s", e)
            raise

#------------------------------------------------------------------
#    Read BufferI3Mean attribute
#------------------------------------------------------------------
    def read_BufferI3Mean(self, attr):
        print "In ", self.get_name(), "::read_BufferI3Mean()"
        
        #    Add your own code here
        try:
            data = self.AlbaElectr.getBufferChannel(3)
            length = len(data)
            mean = sum(data) / length
            attr.set_value(mean)
        except Exception, e:
            self.my_logger.error("Exception reading BufferI3Mean: %s", e)
            raise

#------------------------------------------------------------------
#    Read BufferI4 attribute
#------------------------------------------------------------------
    def read_BufferI4(self, attr):
        print "In ", self.get_name(), "::read_BufferI4()"
        
        #    Add your own code here
        try:
            data = self.AlbaElectr.getBufferChannel(4)
            length = len(data)
            attr.set_value(data, length)
        except Exception, e:
            self.my_logger.error("Exception reading BufferI4: %s", e)
            raise

#------------------------------------------------------------------
#    Read BufferI4Mean attribute
#------------------------------------------------------------------
    def read_BufferI4Mean(self, attr):
        print "In ", self.get_name(), "::read_BufferI4Mean()"
        
        #    Add your own code here
        try:
            data = self.AlbaElectr.getBufferChannel(4)
            length = len(data)
            mean = sum(data) / length
            attr.set_value(mean)
        except Exception, e:
            self.my_logger.error("Exception reading BufferI4Mean: %s", e)
            raise

#------------------------------------------------------------------
#    My own methods
#------------------------------------------------------------------
    def checkRanges(self,attr,current,axis):

        dictMinRanges = {'1mA':1e-6,'100uA':1e-7,'10uA':1e-8,'1uA':1e-9,'100nA':1e-10,'10nA':1e-11,'1nA':1e-12,'100pA':1e-13}
        dictMaxRanges = {'1mA':1e-3,'100uA':1e-4,'10uA':1e-5,'1uA':1e-6,'100nA':1e-7,'10nA':1e-8,'1nA':1e-9,'100pA':1e-10}
        
        if math.fabs(current) >= dictMaxRanges[self.AllRanges[axis]]:
            attr.set_quality(PyTango.AttrQuality.ATTR_ALARM)
        elif math.fabs(current) <= dictMinRanges[self.AllRanges[axis]]:
            attr.set_quality(PyTango.AttrQuality.ATTR_WARNING)
        else:
            #self.set_state(PyTango.DevState.ON)
            attr.set_quality(PyTango.AttrQuality.ATTR_VALID)
            #pass
            
    def checkAlbaEmState(self):
        state = self.AlbaElectr.getState()
        
        if state == 'ON': self.set_state(PyTango.DevState.ON)
        elif state == 'RUNNING': self.set_state(PyTango.DevState.RUNNING)
        elif state == 'IDLE': self.set_state(PyTango.DevState.STANDBY)
        else: self.set_state(PyTango.DevState.UNKNOWN)
            
    def readMeasure(self,axis):
        attr = float(self.AlbaElectr.getMeasure(str(axis)))
        return attr
        #attr.set_value(self.attr_I2_read)
        
    def readBufferChannel(self,axis):
        attr = self.AlbaElectr.getBufferChannel(axis)
        return attr
    
    def readBufferMean(self,axis):
        attr = self.AlbaElectr.getBufferChannel(axis)
        length = len(attr)
        mean = sum(attr) / length
        return mean
        
        
#==================================================================
#
#    PyAlbaEm command methods
#
#==================================================================

    def StopAdc(self):
        self.AlbaElectr.StopAdc()
     
    def Stop(self):
        self.AlbaElectr.Stop()       
    
    def StartAdc(self):
        self.AlbaElectr.StartAdc()
    
    def Start(self):
        self.AlbaElectr.Start()
        
    def enableChannel(self,axis):
        self.AlbaElectr.enableChannel(axis)
    
    def setAvsamples(self,value):
        self.AlbaElectr.setAvsamples(value)
        
    def setTrigperiode(self,value):
        self.AlbaElectr.setTrigperiod(value)
        
    def setPoints(self,value):
        self.AlbaElectr.setPoints(value)

#==================================================================
#
#    PyAlbaEmClass class definition
#
#==================================================================
class PyAlbaEmClass(fandango.DynamicDSClass):

    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        'AlbaEmName':
            [PyTango.DevString,
            "name or ip of the Alba Electrometer",
            [] ],
        'DynamicAttributes':
            [PyTango.DevVarStringArray,
            "",
            [] 
            ],
        'LogFileName':
            [PyTango.DevString,
            "",
            [] 
            ],
        }

    #    Command definitions
    cmd_list = {
        'updateDynamicAttributes':
            [[PyTango.DevVoid, ""],
            [PyTango.DevVoid, ""],
            {
                'Display level':PyTango.DispLevel.EXPERT,
             } ],
        'Stop':
            [[PyTango.DevVoid, ""],
            [PyTango.DevVoid, ""],
            {
             } ],
        'Start':
            [[PyTango.DevVoid, ""],
            [PyTango.DevVoid, ""],
            {
             } ],
        'StopAdc':
            [[PyTango.DevVoid, ""],
            [PyTango.DevVoid, ""],
            {
             } ],
        'StartAdc':
            [[PyTango.DevVoid, ""],
            [PyTango.DevVoid, ""],
            {
             } ],
        'enableChannel':
            [[PyTango.DevShort, ""],
            [PyTango.DevVoid, ""],
            {
             } ],
        'setAvsamples':
            [[PyTango.DevDouble, ""],
            [PyTango.DevVoid, ""],
            {
             } ],
        'setTrigperiode':
            [[PyTango.DevDouble, ""],
            [PyTango.DevVoid, ""],
            {
             } ],
        'setPoints':
            [[PyTango.DevDouble, ""],
            [PyTango.DevVoid, ""],
            {
             } ],
        }


    #    Attribute definitions
    attr_list = {
        'I1':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'I2':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'I3':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'I4':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'AllChannels':
            [[PyTango.DevDouble,
            PyTango.SPECTRUM,
            PyTango.READ, 4]],
        'LastValues':
            [[PyTango.DevDouble,
            PyTango.SPECTRUM,
            PyTango.READ, 4]],
        'range_ch1':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'range_ch2':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'range_ch3':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'range_ch4':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'Ranges':
            [[PyTango.DevString,
            PyTango.SPECTRUM,
            PyTango.READ_WRITE, 4],
            {
                'description':"You must introduce the four ranges to write.\nExample of writing value: 1mA 1mA 1uA 100uA"
            }
            ],
        'filter_ch1':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'filter_ch2':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'filter_ch3':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'filter_ch4':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'Filters':
            [[PyTango.DevString,
            PyTango.SPECTRUM,
            PyTango.READ_WRITE, 4],
            {
                'description':"You must introduce the four filters to write.\nExample of writing value: 1 10 100 NO "
            }
            ],
        'ChannelsNames':
            [[PyTango.DevString,
            PyTango.SPECTRUM,
            PyTango.READ_WRITE, 4],
            {
                'description':"Channels names. Must be the same names that already exists for pool channels.",
                'memorized': True
            }
            ],
#        'LogRecord':
#            [[PyTango.DevBoolean,
#            PyTango.SCALAR,
#            PyTango.READ_WRITE]],
        'TriggerMode':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'description':"Trigger mode for acquiring. Could be INT or EXT",
            }
            ],
        'TriggerPeriod':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'description':"Trigger period in seconds",
            }
            ],
        'BufferSize':
            [[PyTango.DevShort,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'description':"Number of points per acquisition",
            }
            ],
        'AvSamples':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'description':"Number of points per acquisition",
            }
            ],
        'BufferI1':
            [[PyTango.DevDouble,
            PyTango.SPECTRUM,
            PyTango.READ, 4096],
            ],
        'BufferI2':
            [[PyTango.DevDouble,
            PyTango.SPECTRUM,
            PyTango.READ, 4096],
            ],
        'BufferI3':
            [[PyTango.DevDouble,
            PyTango.SPECTRUM,
            PyTango.READ, 4096],
            ],
        'BufferI4':
            [[PyTango.DevDouble,
            PyTango.SPECTRUM,
            PyTango.READ, 4096],
            ],
        'BufferI1Mean':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ],
            ],
        'BufferI2Mean':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ],
            ],
        'BufferI3Mean':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ],
            ],
        'BufferI4Mean':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ],
            ],
        }


#------------------------------------------------------------------
#    PyAlbaEmClass Constructor
#------------------------------------------------------------------
    def __init__(self, name):
        PyTango.DeviceClass.__init__(self, name)
        self.set_type(name);
        print "In PyAlbaEmClass  constructor"

#==================================================================
#
#    PyAlbaEm class main method
#
#==================================================================
if __name__ == '__main__':
    #logging example taurus/core/util/log.py (format)
    try:
        py = PyTango.Util(sys.argv)
        py.add_TgClass(PyAlbaEmClass,PyAlbaEm,'PyAlbaEm')

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed,e:
        print '-------> Received a DevFailed exception:',e
    except Exception,e:
        print '-------> An unforeseen exception occured....',e
